DROP TABLE IF EXISTS maps CASCADE;

-- Maps
CREATE TABLE maps (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  map_point INTEGER REFERENCES map_points(id) ON DELETE CASCADE,
  favourite_map INTEGER REFERENCES favourite_maps(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL
);